In [3]:
import pandas as pd

* Carregamento dos Dados (últimas 22 temporadas - Brasileirão)

In [12]:
df = pd.read_csv(r"C:\Users\Jorda\OneDrive\Documentos\Projetos de portfolio\BestBrazilianTeam\data\brasileirao.csv")

df

,season,place,team,points,played,won,draw,loss,goals,goals_taken,goals_diff
0,2003,1,Cruzeiro,100,46,31,7,8,102,47,55
1,2003,2,Santos,87,46,25,12,9,93,60,33
2,2003,3,São Paulo,78,46,22,12,12,81,67,14
3,2003,4,São Caetano,74,46,19,14,13,53,37,16
4,2003,5,Coritiba,73,46,21,10,15,67,58,9
...,...,...,...,...,...,...,...,...,...,...,...
465,2025,16,Internacional,44,38,11,11,16,44,57,-13
466,2025,17,Ceara,43,38,11,10,17,34,40,-6
467,2025,18,Fortaleza,43,38,11,10,17,43,58,-15
468,2025,19,Juventude,35,38,9,8,21,35,69,-34
469,2025,20,Sport,17,38,2,11,25,28,75,-47

In [14]:
df["percentual_vitorias"] = df["won"] / df["played"]*100
df["media_gols_marcados"] = df["goals"] / df["played"]
df["media_gols_sofridos"] = df["goals_taken"] / df["played"]

#Visualizar dados
df

,season,place,team,points,played,won,draw,loss,goals,goals_taken,goals_diff,percentual_vitorias,media_gols_marcados,media_gols_sofridos
0,2003,1,Cruzeiro,100,46,31,7,8,102,47,55,67.391304,2.217391,1.021739
1,2003,2,Santos,87,46,25,12,9,93,60,33,54.347826,2.021739,1.304348
2,2003,3,São Paulo,78,46,22,12,12,81,67,14,47.826087,1.760870,1.456522
3,2003,4,São Caetano,74,46,19,14,13,53,37,16,41.304348,1.152174,0.804348
4,2003,5,Coritiba,73,46,21,10,15,67,58,9,45.652174,1.456522,1.260870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,2025,16,Internacional,44,38,11,11,16,44,57,-13,28.947368,1.157895,1.500000
466,2025,17,Ceara,43,38,11,10,17,34,40,-6,28.947368,0.894737,1.052632
467,2025,18,Fortaleza,43,38,11,10,17,43,58,-15,28.947368,1.131579,1.526316
468,2025,19,Juventude,35,38,9,8,21,35,69,-34,23.684211,0.921053,1.815789
469,2025,20,Sport,17,38,2,11,25,28,75,-47,5.263158,0.736842,1.973684

* Analisando os mariores campeoes da historia... quais as caracteristicas dos campeoes? Há um padrao? Quem é o maior vencedor dos ultimos anos?

In [15]:
# Filtrar dataset com os campeoes de cada ano
filtro_campeoes = df["place"] == 1

# aplicar filtro ao dataset
df_campeoes = df[filtro_campeoes]

#Visualizando dados
df_campeoes

,season,place,team,points,played,won,draw,loss,goals,goals_taken,goals_diff,percentual_vitorias,media_gols_marcados,media_gols_sofridos
0,2003,1,Cruzeiro,100,46,31,7,8,102,47,55,67.391304,2.217391,1.021739
24,2004,1,Santos,89,46,27,8,11,103,58,45,58.695652,2.239130,1.260870
48,2005,1,Corinthians,81,42,24,9,9,87,59,28,57.142857,2.071429,1.404762
70,2006,1,São Paulo,78,38,22,12,4,66,32,34,57.894737,1.736842,0.842105
90,2007,1,São Paulo,77,38,23,8,7,55,19,36,60.526316,1.447368,0.500000
110,2008,1,São Paulo,75,38,21,12,5,66,36,30,55.263158,1.736842,0.947368
130,2009,1,Flamengo,67,38,19,10,9,58,44,14,50.000000,1.526316,1.157895
150,2010,1,Fluminense,71,38,20,11,7,62,36,26,52.631579,1.631579,0.947368
170,2011,1,Corinthians,71,38,21,8,9,53,36,17,55.263158,1.394737,0.947368
190,2012,1,Fluminense,77,38,22,11,5,61,33,28,57.894737,1.605263,0.868421
210,2013,1,Cruzeiro,76,38,23,7,8,77,37,40,60.526316,2.026316,0.973684
230,2014,1,Cruzeiro,80,38,24,8,6,67,38,29,63.157895,1.763158,1.000000
250,2015,1,Corinthians,81,38,24,9,5,71,31,40,63.157895,1.868421,0.815789
270,2016,1,Palmeiras,80,38,24,8,6,62,32,30,63.157895,1.631579,0.842105
290,2017,1,Corinthians,72,38,21,9,8,50,30,20,55.263158,1.315789,0.789474
310,2018,1,Palmeiras,80,38,23,11,4,64,26,38,60.526316,1.684211,0.684211
330,2019,1,Flamengo,90,38,28,6,4,86,37,49,73.684211,2.263158,0.973684
350,2020,1,Flamengo,71,38,21,8,9,68,48,20,55.263158,1.789474,1.263158
370,2021,1,Atlético Mineiro,84,38,26,6,6,67,34,33,68.421053,1.763158,0.894737
390,2022,1,Palmeiras,81,38,23,12,3,66,27,39,60.526316,1.736842,0.710526
410,2023,1,Palmeiras,70,38,20,10,8,64,33,31,52.631579,1.684211,0.868421
430,2024,1,Botafogo,79,38,23,10,5,59,29,30,60.526316,1.552632,0.763158
450,2025,1,Flamengo,79,38,23,10,5,78,27,51,60.526316,2.052632,0.710526

In [16]:
# Descobrindo o maior campeão dos ultimos anos
df_campeoes["team"].mode()

0    Corinthians
1       Flamengo
2      Palmeiras
Name: team, dtype: object

In [18]:
df_campeoes.groupby("team")["place"].count().sort_values(ascending=False)

team
Corinthians         4
Palmeiras           4
Flamengo            4
São Paulo           3
Cruzeiro            3
Fluminense          2
Atlético Mineiro    1
Botafogo            1
Santos              1
Name: place, dtype: int64

In [19]:
# Analisando estatisticas e padroes dos campeões

df_campeoes.describe()

,season,place,points,played,won,draw,loss,goals,goals_taken,goals_diff,percentual_vitorias,media_gols_marcados,media_gols_sofridos
count,23.00000,23.0,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,2014.00000,1.0,78.652174,38.869565,23.173913,9.130435,6.565217,69.217391,36.043478,33.173913,59.568344,1.771238,0.921190
std,6.78233,0.0,7.383081,2.398946,2.774104,1.841549,2.106831,13.960843,9.683530,10.611538,5.465443,0.265547,0.206773
min,2003.00000,1.0,67.000000,38.000000,19.000000,6.000000,3.000000,50.000000,19.000000,14.000000,50.000000,1.315789,0.500000
25%,2008.50000,1.0,73.500000,38.000000,21.000000,8.000000,5.000000,61.500000,30.500000,28.000000,55.263158,1.618421,0.802632
50%,2014.00000,1.0,79.000000,38.000000,23.000000,9.000000,6.000000,66.000000,34.000000,31.000000,60.526316,1.736842,0.894737
75%,2019.50000,1.0,81.000000,38.000000,24.000000,10.500000,8.000000,74.000000,37.500000,39.500000,61.842105,1.947368,0.986842
max,2025.00000,1.0,100.000000,46.000000,31.000000,12.000000,11.000000,103.000000,59.000000,55.000000,73.684211,2.263158,1.404762

In [21]:
# Qual foi o time com maior percentual de vitorias
indice_maior_campeao = df_campeoes["percentual_vitorias"].idxmax()

df_campeoes.loc[indice_maior_campeao]

season                      2019
place                          1
team                    Flamengo
points                        90
played                        38
won                           28
draw                           6
loss                           4
goals                         86
goals_taken                   37
goals_diff                    49
percentual_vitorias    73.684211
media_gols_marcados     2.263158
media_gols_sofridos     0.973684
Name: 330, dtype: object

In [22]:
# Qual foi o time com a melhor defesa
indice_maior_defesa = df_campeoes["media_gols_sofridos"].idxmin()

df_campeoes.loc[indice_maior_defesa]

season                      2007
place                          1
team                   São Paulo
points                        77
played                        38
won                           23
draw                           8
loss                           7
goals                         55
goals_taken                   19
goals_diff                    36
percentual_vitorias    60.526316
media_gols_marcados     1.447368
media_gols_sofridos          0.5
Name: 90, dtype: object